apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot
  namespace: openfaas-fn
  labels:
    app: robot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robot
  template:
    metadata:
      labels:
        app: robot
        criticality: be
    spec:
    #  schedulerName: rtfaas-scheduler
      nodeSelector:
        job: "robot"
      containers:
      - name: robot
        image: botondbencs/edfrobotcontainer_ld2
        command: ["./myapp","50","10"]  # Substitute timeout and fps here
      # nodeSelector:
      #   job: "robot"
