apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      com.openfaas.k8s.node-selector: kubernetes.io/hostname=beta
      prometheus.io.scrape: "false"
      rt-p-ms: "10"
      rt-q-ms: "4"
    creationTimestamp: "2026-06-03T18:56:18Z"
    generateName: pidserver-678486995-
    generation: 1
    labels:
      criticality: rt
      faas_function: pidserver
      pod-template-hash: "678486995"
      uid: "575399965"
    name: pidserver-678486995-9g7zb
    namespace: openfaas-fn
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: pidserver-678486995
      uid: 1c1c9c51-33be-4f84-8572-9e854860dca1
    resourceVersion: "9203722"
    uid: 15b4644f-fd74-4259-b887-afc5853a8420
  spec:
    containers:
    - env:
      - name: EDFDEADLINE
        value: "10"
      - name: EDFPERIOD
        value: "10"
      - name: EDFRUNTIME
        value: "4"
      - name: fprocess
        value: python index.py
      image: botondbencs/edf-pidserver:latest
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /_/health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 2
        successThreshold: 1
        timeoutSeconds: 1
      name: pidserver
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /_/health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 2
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 400m
        requests:
          cpu: 400m
      securityContext:
        privileged: true
        readOnlyRootFilesystem: false
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-rgww6
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: beta
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: rtfaas-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-rgww6
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:51:18Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:51:16Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:51:19Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:51:19Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:56:19Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 400m
      containerID: containerd://6f21cdcbbdc7b4ca4aa0e01f9a8eb2a6497cf040b82b56b89d156e922bde1fdb
      image: docker.io/botondbencs/edf-pidserver:latest
      imageID: docker.io/botondbencs/edf-pidserver@sha256:bd50c83ba81c706b2240ba1ef02ab3d5d704054e546e12750d182a5d8a4eb5e0
      lastState: {}
      name: pidserver
      ready: true
      resources:
        limits:
          cpu: 400m
        requests:
          cpu: 400m
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-06-03T18:51:17Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          uid: 0
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-rgww6
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 192.168.0.201
    hostIPs:
    - ip: 192.168.0.201
    observedGeneration: 1
    phase: Running
    podIP: 10.244.1.180
    podIPs:
    - ip: 10.244.1.180
    qosClass: Burstable
    startTime: "2026-06-03T18:51:16Z"
kind: List
metadata:
  resourceVersion: ""
