apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      com.openfaas.k8s.node-selector: kubernetes.io/hostname=beta
      prometheus.io.scrape: "false"
    creationTimestamp: "2026-06-03T18:36:15Z"
    generateName: pidserver-cbdb5cd77-
    generation: 1
    labels:
      criticality: be
      faas_function: pidserver
      pod-template-hash: cbdb5cd77
      uid: "505800959"
    name: pidserver-cbdb5cd77-6kxcz
    namespace: openfaas-fn
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: pidserver-cbdb5cd77
      uid: 289748d6-3f25-4a7e-980d-aa7b57cf36f7
    resourceVersion: "9201497"
    uid: 06640e11-53b9-4a57-9c80-6e0a51f25b6f
  spec:
    containers:
    - env:
      - name: fprocess
        value: python index.py
      image: botondbencs/edf-pidserver:latest
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /_/health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 2
        successThreshold: 1
        timeoutSeconds: 1
      name: pidserver
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /_/health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 2
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      securityContext:
        privileged: false
        readOnlyRootFilesystem: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-bmr27
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: beta
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-bmr27
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:31:14Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:31:12Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:31:17Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:31:17Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:36:15Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://340fae3f25913236925ff93cbb4972a2d8338e96da2c9a6eddf16a759b4cfb95
      image: docker.io/botondbencs/edf-pidserver:latest
      imageID: docker.io/botondbencs/edf-pidserver@sha256:bd50c83ba81c706b2240ba1ef02ab3d5d704054e546e12750d182a5d8a4eb5e0
      lastState: {}
      name: pidserver
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-06-03T18:31:14Z"
      user:
        linux:
          gid: 101
          supplementalGroups:
          - 101
          uid: 100
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-bmr27
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 192.168.0.201
    hostIPs:
    - ip: 192.168.0.201
    observedGeneration: 1
    phase: Running
    podIP: 10.244.1.175
    podIPs:
    - ip: 10.244.1.175
    qosClass: BestEffort
    startTime: "2026-06-03T18:31:12Z"
kind: List
metadata:
  resourceVersion: ""
