apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"rtfaas-cpu-stressor","measurement":"k8s-highprio-cpu","mode":"gd"},"name":"rtfaas-cpu-stressor-gd-1780569908","namespace":"default"},"spec":{"containers":[{"command":["sh","-c","echo starting k8s high-priority CPU stressor mode=gd\nfor i in 1 2 3 4; do python -c \"while True: pass\" \u0026 done\nwait\n"],"image":"botondbencs/edf-pidserver:latest","imagePullPolicy":"IfNotPresent","name":"stressor","resources":{"limits":{"memory":"256Mi"},"requests":{"cpu":"3500m","memory":"64Mi"}}}],"nodeSelector":{"kubernetes.io/hostname":"beta"},"priorityClassName":"rtfaas-high-priority-stressor","restartPolicy":"Never"}}
  creationTimestamp: "2026-06-04T10:45:08Z"
  generation: 1
  labels:
    app: rtfaas-cpu-stressor
    measurement: k8s-highprio-cpu
    mode: gd
  name: rtfaas-cpu-stressor-gd-1780569908
  namespace: default
  resourceVersion: "9290762"
  uid: 61af9f27-d0d9-4682-aac3-f4774adb6436
spec:
  containers:
  - command:
    - sh
    - -c
    - |
      echo starting k8s high-priority CPU stressor mode=gd
      for i in 1 2 3 4; do python -c "while True: pass" & done
      wait
    image: botondbencs/edf-pidserver:latest
    imagePullPolicy: IfNotPresent
    name: stressor
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 3500m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hb22m
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: beta
  nodeSelector:
    kubernetes.io/hostname: beta
  preemptionPolicy: PreemptLowerPriority
  priority: 1000000
  priorityClassName: rtfaas-high-priority-stressor
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-hb22m
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-06-04T10:40:03Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-06-04T10:40:02Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-06-04T10:40:03Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-06-04T10:40:03Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-06-04T10:45:08Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 3500m
      memory: 64Mi
    containerID: containerd://7f9246b82ea82a282341acd559fb882e4033120e2bbae1223f47b0ee50528ac4
    image: docker.io/botondbencs/edf-pidserver:latest
    imageID: docker.io/botondbencs/edf-pidserver@sha256:bd50c83ba81c706b2240ba1ef02ab3d5d704054e546e12750d182a5d8a4eb5e0
    lastState: {}
    name: stressor
    ready: true
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 3500m
        memory: 64Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-06-04T10:40:03Z"
    user:
      linux:
        gid: 101
        supplementalGroups:
        - 101
        uid: 100
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hb22m
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.0.201
  hostIPs:
  - ip: 192.168.0.201
  observedGeneration: 1
  phase: Running
  podIP: 10.244.1.191
  podIPs:
  - ip: 10.244.1.191
  qosClass: Burstable
  startTime: "2026-06-04T10:40:02Z"
