apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      com.openfaas.k8s.node-selector: kubernetes.io/hostname=beta
      prometheus.io.scrape: "false"
    creationTimestamp: "2026-06-03T18:38:38Z"
    generateName: pidserver-79d8c8968f-
    generation: 1
    labels:
      criticality: be
      faas_function: pidserver
      pod-template-hash: 79d8c8968f
      uid: "703130599"
    name: pidserver-79d8c8968f-2ffwg
    namespace: openfaas-fn
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: pidserver-79d8c8968f
      uid: b59a5d8b-2abc-4a37-90b0-fcf604f86cff
    resourceVersion: "9201797"
    uid: 3eae4b3d-1193-4598-9754-dcf36886989f
  spec:
    containers:
    - env:
      - name: fprocess
        value: python index.py
      image: botondbencs/edf-pidserver:latest
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /_/health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 2
        successThreshold: 1
        timeoutSeconds: 1
      name: pidserver
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /_/health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 2
        periodSeconds: 2
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 300m
        requests:
          cpu: 300m
      securityContext:
        privileged: false
        readOnlyRootFilesystem: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-8287d
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: beta
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-8287d
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:33:37Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:33:35Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:33:40Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:33:40Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-06-03T18:38:38Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 300m
      containerID: containerd://19b631afa9d280f93ed9b69fa00b12d311c1d5de46a774c14643033c35ab8c21
      image: docker.io/botondbencs/edf-pidserver:latest
      imageID: docker.io/botondbencs/edf-pidserver@sha256:bd50c83ba81c706b2240ba1ef02ab3d5d704054e546e12750d182a5d8a4eb5e0
      lastState: {}
      name: pidserver
      ready: true
      resources:
        limits:
          cpu: 300m
        requests:
          cpu: 300m
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-06-03T18:33:37Z"
      user:
        linux:
          gid: 101
          supplementalGroups:
          - 101
          uid: 100
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-8287d
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 192.168.0.201
    hostIPs:
    - ip: 192.168.0.201
    observedGeneration: 1
    phase: Running
    podIP: 10.244.1.176
    podIPs:
    - ip: 10.244.1.176
    qosClass: Burstable
    startTime: "2026-06-03T18:33:35Z"
kind: List
metadata:
  resourceVersion: ""
